site_config_file: config/site.yml
pages_directory: pages
assets_directory: assets

version:
  server: "1.0"
  application: "1.0"
  server_config_file: server_config.yml
  site_config_file: config/site.yml

cors_mapping:
  'http://vjs-dev-host:8080': 'http://vjs-dev-host:8888'

base_url_bck: "#"
assets_url: "http://vjs-dev-host:8888/api/assets/"
sitemap_root: "http://vjs-dev-host:8080/#"