version: "3.4"

services:

  app:
    build:
      context: .
      dockerfile: otvl-web-sample/Dockerfile
    image: ${OTVL_WEB_REGISTRY:-otvl-dkr-host:9080}/otvl-web-sample-app:${OTVL_WEB_VERSION:-v2.0.0}
    ports:
      - "8081:80"
    environment:
      - OTVL_WEB_SERVER_NAME=${OTVL_WEB_SERVER_NAME:-otvl-dcdev-host}
      - OTVL_WEB_APP_PORT=${OTVL_WEB_APP_PORT:-9443}
      - OTVL_WEB_ENABLE_BOTS=${OTVL_WEB_ENABLE_BOTS:-}
    volumes:
      - ${OTVL_WEB_ASSETS_PATH:-./server/data/demo_app/assets}:/assets

  api:
    build:
      context: ./server
    image: ${OTVL_WEB_REGISTRY:-otvl-dkr-host:9080}/otvl-web-sample-api:${OTVL_WEB_VERSION:-v2.0.0}
    ports:
      - "9091:9090"
    environment:
      - OTVL_WEB_LOGGING=DEBUG
    volumes:
      - ${OTVL_WEB_APP_DATA_PATH:-./server/data/demo_app}:/data
