version: "3.4"

services:

  otvl-web-sample:
    build:
      context: .
      dockerfile: otvl-web-sample/Dockerfile
    ports:
      - "8080:80"
    environment:
      - OTVL_WEB_SERVER_NAME=otvl-dev-host
      - OTVL_WEB_APP_PORT=9443
      - OTVL_WEB_ENABLE_BOTS=1
    volumes:
      - ./server/data/demo_app/assets:/assets

  api:
    build:
      context: ./server
    ports:
      - "9090:9090"
    environment:
      - OTVL_WEB_LOGGING=DEBUG
    volumes:
      - ./server/data/demo_app:/data

  reverse-proxy:
    image: traefik:v2.4
    command: --configFile=/traefik/static_config.yml
    ports:
      - "9443:443"
      - "9180:8080"
    volumes:
      - ./otvl-web-sample/traefik/dev:/traefik
