site_config_file: data/test_site1/config/site1.yml

version:
  server: "1.0"
  application: "1.0"
  server_config_file: server/config/server.yml
  site_config_file: data/test_site1/config/site1.yml

cors_mapping:
  'http://vjs-dev-host:8080': 'http://vjs-dev-host:8888'
