version: "3.3"

services:
  server:
    image: "${VAR_ACT_S_IMAGE}"
    volumes:
      - ${VAR_DATA_TMP}:/srv/ext/data

    environment:
      SRV_DATA: "/srv/ext/data"
    ports:
      - "9999:9991"
    hostname: "otvl-web-server"
    container_name: "owc-server"

  vuejs:
    image: "${VAR_ACT_V_IMAGE}"
    volumes:
      - ${VAR_DATA_TMP}/assets:/srv/data/assets
    ports:
      - "9989:9981"
    hostname: "otvl-web-vuejs"
    container_name: "owc-vuejs"

  rpx:
    depends_on:
      - server
      - vuejs
    image: "${VAR_ACT_R_IMAGE}"
    ports:
      - "9443:443"
    hostname: "otvl-web-revproxy"
    container_name: "owc-revproxy"
    links:
      - "server:otvl-web-server"
      - "vuejs:otvl-web-vuejs"
